version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=${FLASK_ENV:-development}
      - FLASK_APP=app.py
      - FLASK_DEBUG=${FLASK_DEBUG:-1}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - CORS_ORIGIN=http://localhost:3000
    networks:
      - app-network
    command: flask run --host=0.0.0.0

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
  backend_modules: 