version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - FLASK_DEBUG=0
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - CORS_ORIGIN=http://localhost
    restart: always
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
      - NODE_ENV=production
    restart: always
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
