services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_APP=${FLASK_APP}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - CORS_ORIGIN=${CORS_ORIGIN}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - REACT_APP_BACKEND_URL=${CORS_ORIGIN}
      - NODE_ENV=${NODE_ENV}
    env_file:
      - .env
      - frontend/.env
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  app-network:
    driver: bridge
