version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - frontend_node_modules:/app/node_modules
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - backend_data:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - CORS_ORIGIN=http://localhost:3000
    networks:
      - app-network
    restart: unless-stopped
    command: flask run --host=0.0.0.0

networks:
  app-network:
    driver: bridge

volumes:
  frontend_node_modules:
  backend_data: 