version: '3.8'

services:
  backend:
    image: ghcr.io/${GITHUB_USERNAME_LOWER}/goatsquad-backend:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    image: ghcr.io/${GITHUB_USERNAME_LOWER}/goatsquad-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

secrets:
  github_token:
    external: true

x-registry-auth: |
  {
    "auths": {
      "ghcr.io": {
        "auth": "${GITHUB_TOKEN_BASE64}"
      }
    }
  }
